name: Docker Image CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: zkrp
    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Login to Container Registry
        uses: docker/login-action@v2.1.0
        with:
            username: ${{vars.USER2}}
            password: ${{secrets.ZKRP}}
            

   
      - name: Build Docker Image
        run: docker build -t "${{vars.USER2}}/${{vars.IMAGENAME}}:0.1.6" .

    
      - name: Push Docker Image
        run: docker push "${{vars.USER2}}/${{vars.IMAGENAME}}:0.1.6"

    # env:
    #   hoeng: ${{ env.hoeng }}
    #   USER: ${{ secrets.USER }}
